name: Poll events

on:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install package
        run: npm i -g @adguard/github-stats
      - name: Poll Github events
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COLLECTION_PATH: ./stats-data
          REPO: AdguardTeam/AdguardFilters
        run: github-poll
      - name: commit artifacts
        uses: EndBug/add-and-commit@v9
        with:
          message: Events collection update
