name: Publish stats (manually)

env:
  NODE_VERSION: 22.14.0

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository path'
        required: true
        type: string
        default: 'AdguardTeam/AdguardFilters'
      since:
        description: 'Timestamp to search from'
        required: false
        type: string
        default: '2022-11-21T09:00:00Z'
      until:
        description: 'Timestamp to search to'
        required: false
        type: string
        default: '2022-11-22T09:00:00Z'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install package
        run: yarn install

      - name: Publish repo stats
        env:
          SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COLLECTION_PATH: ./stats-data
          REPO: ${{ github.event.inputs.repo }}
          SINCE: ${{ github.event.inputs.since }}
          UNTIL: ${{ github.event.inputs.until }}
        run: node -r esm ./bin/github-publish.js
  notify:
    needs: stats
    # Run this job only if the previous job failed
    # Note: 'always()' is needed to run the notify job even if the poll job was failed
    if: ${{ always() && needs.stats.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: workflow, repo, message, commit, author, eventName, ref, job
          job_name: stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
